

#- name: Install Docker Python (Debian/Ubuntu)
#  package:
#   name: python3-docker
#   state: present
#  become: yes
#  when: ansible_distribution in ["Debian", "Ubuntu"]
#
#- name: Install Docker Python (Red Hat/CentOS/Fedora)
#  pip:
#    name: docker
#    state: present
#  become: yes
#  when: ansible_distribution in ["RedHat", "CentOS", "Fedora"]

- name: Python pip install
  package:
    name: python3-pip
    state: present
  become: yes

# --- УСТАНОВКА DOCKER НА DEBIAN/UBUNTU ---
- name: Install packages for Docker 
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add Docker GPG key 
  ansible.builtin.apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add Docker repository 
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  become: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Docker ce install 
  apt:
    name: docker-ce
    update_cache: yes
    state: present
  become: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

# --- УСТАНОВКА DOCKER НА RED HAT
- name: Install packages for Docker 
  package:
    name:
      - dnf-plugins-core
    state: present
  become: yes
  when: ansible_distribution in ["RedHat", "CentOS", "Fedora", "AlmaLinux"]

- name: Add Docker repository 
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: yes
  when: ansible_distribution in ["RedHat", "CentOS", "Fedora", "AlmaLinux"]

- name: Install Docker 
  package:
    name: docker-ce
    state: present
  become: yes
  when: ansible_distribution in ["RedHat", "CentOS", "Fedora", "AlmaLinux"]

# --- ОБЩАЯ ЧАСТЬ ДЛЯ ВСЕХ ОС ---
- name: Docker start
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Create Docker group 
  group:
    name: docker
    state: present
  become: yes

- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: yes
  notify: restart docker